### ISSUE TITLE
Regex driven nose command line options throw error.

### ISSUE THREAD

**Issue by johnnoz** [django-nose/django-nose#242] opened 2015-11-09 23:01 UTC
I am using Django 1.8.4 and django-nose 1.4.2

When attempting to use the nose command line options -i, -I or -e, regardless of what is passed to them an error is thrown

```
python manage.py test -I="blah" test_app
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 384, in run_from_argv
    options = parser.parse_args(argv[2:])
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 64, in parse_args
    return super(CommandParser, self).parse_args(args, namespace)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1701, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1939, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1879, in consume_optional
    take_action(action, args, option_string)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1807, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 930, in __call__
    items.append(values)
AttributeError: 'tuple' object has no attribute 'append'
```

all options that don't expect regex appear to work as intended.

It's entirely possible I'm doing something wrong here, but this is a very strange error to see!

**Comment by jwhitlock** [comment] 2015-11-09 23:10
Duplicate of bug #240 , fixed in with #241 in master

**Closed by jwhitlock** 2015-11-09 23:10 UTC
