### ISSUE TITLE
Models from apps have 0% coverage

### ISSUE THREAD

**Issue by NareshKosgi** [django-nose/django-nose#234] opened 2015-09-29 20:49 UTC
When I run python manage.py or coverage to run tests.  It always show 0% coverage for my models.  Using django 1.8.  I tried the solutions mentioned here:

https://github.com/django-nose/django-nose/issues/180

but no dice.  Anyone else seeing this issue?  Also when I was using 1.6 the same tests would show coverage (almost all at 100%).

**Comment by jwhitlock** [comment] 2015-10-01 15:14
This usually works for me (using ``open`` on a MacBook):
```
coverage erase
coverage run --branch ./manage.py test
coverage report -m
coverage html
open htmlcov/index.html
```

I use [.coveragerc](http://coverage.readthedocs.org/en/latest/config.html) (or setup.cfg with coverage 4.0) to configure some common options, like limiting the reports to my modules and excluding command line scripts from the coverage numbers.

**Comment by jwhitlock** [comment] 2015-10-07 14:54
Closing as duplicate of #180

**Closed by jwhitlock** 2015-10-07 14:54 UTC
