### ISSUE TITLE
Python 3.4 changes in "types.MethodType" affect to REUSE_DB option

### ISSUE THREAD

**Issue by Marakuba** [django-nose/django-nose#181] opened 2015-01-09 19:17 UTC
Trying to set REUSE_DB=1 under Python 3.4 error raised:

> File "lib/python3.4/site-packages/django_nose/runner.py", line 395, in setup_databases
>     _skip_create_test_db, creation, creation.__class__)
> TypeError: method expected 2 arguments, got 3

Since MethodType takes only two arguments and third argument `creation.__class__` no longer needs in this case.

**Comment by jwhitlock** [comment] 2015-04-23 21:02
Duplicate of #122

**Closed by jwhitlock** 2015-04-23 21:02 UTC
