### ISSUE TITLE
REUSE_DB=1 throws exception with Django==1.8

### ISSUE THREAD

**Issue by flaviamissi** [django-nose/django-nose#212] opened 2015-05-31 10:55 UTC
Versions:
```
Django==1.8
nose==1.3.6
django-nose==1.4
```

Exception:
```
  File "/Users/flaviamissi/.virtualenvs/extreme-example/lib/python2.7/site-packages/django_nose/runner.py", line 522, in setup_databases
    transaction.commit_unless_managed(using=connection.alias)
AttributeError: 'module' object has no attribute 'commit_unless_managed'
```

First time runs fine (when it does create a database). Second time fails with the above exception.

**Comment by jwhitlock** [comment] 2015-07-02 20:55
Duplicate of #197

**Closed by jwhitlock** 2015-07-02 20:55 UTC
