### ISSUE TITLE
Django==1.8 and django-nose==1.4.1: 'module' object has no attribute 'enter_transaction_management'

### ISSUE THREAD

**Issue by danigosa** [django-nose/django-nose#217] opened 2015-06-30 18:20 UTC
When using Django 1.8, PostgreSQL94 and django_nose.FastFixtureTestCase I got this error:

      Traceback (most recent call last):
       File "/home/vagrant/devenv_dj18/local/lib/python2.7/site-packages/nose/suite.py", line 209, in run
       self.setUp()
       File "/home/vagrant/devenv_dj18/local/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
       self.setupContext(ancestor)
       File "/home/vagrant/devenv_dj18/local/lib/python2.7/site-packages/nose/suite.py", line 315, in      setupContext
       try_run(context, names)
       File "/home/vagrant/devenv_dj18/local/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
       return func()
       File "/home/vagrant/devenv_dj18/local/lib/python2.7/site-packages/django_nose/testcases.py", line 48, in setUpClass
       transaction.enter_transaction_management(using=db)
       AttributeError: 'module' object has no attribute 'enter_transaction_management'

If I switch to django.test.TestCase it works fine. Just a very simple test with a simple fixture is loaded, nothing complex. 

     (devenv_dj18)vagrant@vagrant-ubuntu-trusty-64:/vagrant$ pip freeze
     coverage==3.7
     Django==1.8.2
     nose==1.3.7
     django-nose==1.4.1

**Comment by jwhitlock** [comment] 2015-07-02 20:51
Duplicate of #197

**Closed by jwhitlock** 2015-07-02 20:51 UTC
