### ISSUE TITLE
selecting tests by attributes does not seem to work

### ISSUE THREAD

**Issue by shalonwood** [django-nose/django-nose#142] opened 2013-10-02 16:30 UTC
If I specify an attribute via -a or --attr, no tests are run. 

If I set NOSE_ATTR, it seems to work, but I can't specify multiple attributes to limit the tests to ones which have all attributes. E.g., NOSE_ATTR='scope=local,hostname' seems to run all tests which have _either_ a scope attribute of local, or a hostname attribute, not both. It's possible I'm not setting NOSE_ATTR correctly, however, as I've never needed to use it before.

We're using django-nose 1.2, nose 1.3, and python 2.6. In our non-django projects, we're able to limit tests this way without issue.

Expected outcome:
Tests can be selected using attributes as per the documentation.

**Comment by fletom** [comment] 2015-02-13 17:25
If I run `./manage.py test -a '!slow'`, the nosetests command printed on the next line is `nosetests -a --verbosity=1`.

If I run `./manage.py test -a'!slow'` it becomes `nosetests -a!slow --verbosity=1` which actually applies the attributes correctly.

So there seems to be a significant bug where putting a space between -a and its argument causes the argument to disappear. Is there any chance this will get fixed @jsocol ? Are you accepting pull requests to fix it?

**Comment by jwhitlock** [comment] 2015-07-02 22:30
Might be related to #206.  I thought this was a new issue with Django 1.8, but it may go back to 2013

**Comment by lanart** [comment] 2015-07-08 13:45
I can confirm that bug is present with Django 1.7.7

**Comment by jwhitlock** [comment] 2015-10-07 14:38
I started to dive into this, and the fix will be longer than expected, so bumping to v1.4.3.

Short version: using ``--option value`` probably won't work (yet), but ``--option=value`` might.

Longer version:

Command line parsing is complicated:

1. django-nose merges nose parse options with Django parse options.  There is a different strategy for Django 1.6 and earlier (using ``optparse``) from Django 1.7 and later (using ``argparse``).
2. Django's management command framework parses the command line
3. Django's test command class interprets some, but not all, of the command line options
4. django-nose reformats the command-line arguments to modify Django-specific options
5. nose's command line parser re-parses the reformatted command-line arguments

The problem is that Django likes ``--option value`` (and this is what ``./manage.py test --help`` will show), but nose likes ``--option=value``.  We're already manipulating the command-line args in step 4, to make things like ``verbosity`` work,  but something more generic is needed for other options with values.  Ideally, we could pass the results of Django's command line parsing to nose and skip the re-parsing steps (4 and 5), but I'm not sure if nose has the right hooks, and it may cause other issues.

**Comment by cderwin** [comment] 2015-12-15 06:06
What's the difference between this issue, #7, and #240 (closed/merged), all of which are slated for the next release?

**Comment by jwhitlock** [comment] 2015-12-15 14:19
The root cause appears to be reconstructing the command line for nose, and might be fixed by the same fix for #7, in branch [handle_more_options](https://github.com/django-nose/django-nose/tree/handle_more_options). I don't use options in my code bases, so I'm not quite sure how it is supposed to work. When I figure it out, I was going to annotate some existing tests, and add some runtest.sh cases to show a subset of tests was selected.  That will confirm that the #7 fix applies to this bug too.

If someone is more familiar with the attributes feature, I can merge the handle_more_options branch to make a PR adding tests easier to write.

#240 is an issue of translating nose's optparse options into Django's argparse options. It falls under the 
"argument parsing" area, which I consider the core of django-nose, making them top priority bugs for me, and scheduled for the next release. Which is late, because holidays take up my spare development time.

**Comment by cderwin** [comment] 2015-12-16 05:05
Sure, makes sense.  I might take a look at handle_more_options but I haven't used optparse and right now don't have the time.  Thanks for the info!

**Closed** 2015-12-28 22:18 UTC
Labels: bug
