### ISSUE TITLE
When I run tests with flag REUSE_DB=1, it breaks due to incompatible api with Django 1.8

### ISSUE THREAD

**Issue by aamirtharaj-rpx** [django-nose/django-nose#205] opened 2015-04-27 15:25 UTC
When I run tests with flag REUSE_DB=1, it breaks due to a removed api from Django 1.8
```
raceback (most recent call last):
  File "./manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/django/core/management/commands/test.py", line 90, in handle
    failures = test_runner.run_tests(test_labels)
  File "/Users/antonyr/projects/office/pa_web/src/django-nose/django_nose/runner.py", line 350, in run_tests
    result = self.run_suite(nose_argv)
  File "/Users/antonyr/projects/office/pa_web/src/django-nose/django_nose/runner.py", line 297, in run_suite
    addplugins=plugins_to_add)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/nose/core.py", line 50, in run
    wrapper = self.config.plugins.prepareTest(test)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/Users/antonyr/projects/office/pa_web/src/django-nose/django_nose/plugin.py", line 76, in prepareTest
    self.old_names = self.runner.setup_databases()
  File "/Users/antonyr/projects/office/pa_web/src/django-nose/django_nose/runner.py", line 522, in setup_databases
    transaction.commit_unless_managed(using=connection.alias)
AttributeError: 'module' object has no attribute 'commit_unless_managed'
```

Guys, it would be great if you could fix it at the earliest.

**Comment by jwhitlock** [comment] 2015-04-28 13:10
Duplicate of #197

**Closed by jwhitlock** 2015-04-28 13:10 UTC
